{
  "id": "c0f534da-4cf4-4cdb-876b-30dbcdcad632",
  "timestamp": 1755917128.5788088,
  "datetime": "2025-08-23T02:45:28.578809",
  "checkpoint_type": "error",
  "stage": "unknown",
  "state_data": {
    "error": "Object of type ResearchConfig is not JSON serializable",
    "traceback": "Traceback (most recent call last):\n  File \"/root/repo/robust_research_execution_engine.py\", line 1040, in execute_research_pipeline\n    self.checkpoint_manager.create_checkpoint(\n  File \"/root/repo/robust_research_execution_engine.py\", line 727, in create_checkpoint\n    json.dump(checkpoint.to_dict(), f, indent=2)\n  File \"/usr/lib/python3.12/json/__init__.py\", line 179, in dump\n    for chunk in iterable:\n  File \"/usr/lib/python3.12/json/encoder.py\", line 432, in _iterencode\n    yield from _iterencode_dict(o, _current_indent_level)\n  File \"/usr/lib/python3.12/json/encoder.py\", line 406, in _iterencode_dict\n    yield from chunks\n  File \"/usr/lib/python3.12/json/encoder.py\", line 406, in _iterencode_dict\n    yield from chunks\n  File \"/usr/lib/python3.12/json/encoder.py\", line 406, in _iterencode_dict\n    yield from chunks\n  File \"/usr/lib/python3.12/json/encoder.py\", line 439, in _iterencode\n    o = _default(o)\n        ^^^^^^^^^^^\n  File \"/usr/lib/python3.12/json/encoder.py\", line 180, in default\n    raise TypeError(f'Object of type {o.__class__.__name__} '\nTypeError: Object of type ResearchConfig is not JSON serializable\n"
  },
  "system_metrics": {},
  "error_context": {
    "exception_type": "TypeError",
    "exception_message": "Object of type ResearchConfig is not JSON serializable"
  },
  "recovery_info": null
}